### ISSUE TITLE
Database modeling

### ISSUE THREAD

**Issue by arcmena** [gabepereira/kordy#8]
## Description

Create database diagram, using [dbdiagram](https://dbdiagram.io) and create sequelize models.

## Implementation

- Create database diagram.
- Create sequelize models.

**Comment by gabepereira** [comment]
We created the database diagram like that:
![Kordy](https://user-images.githubusercontent.com/17131023/83219829-c51d4080-a147-11ea-8063-40ca70f91efb.png)
